#!/usr/bin/env python3
"""
Build a single self-contained versus_airlines.lua from the modular
src/ tree.

Strategy (much simpler than the first attempt):
    1.  Read every file in dependency order.
    2.  Rewrite `require("src.X.Y")` -> `Y` (just the local name).
    3.  Replace the file's trailing `return X` with `X = <expr>`. Lua
        treats a top-level assignment as a statement; the variable
        becomes a top-level local in the chunk.
    4.  For data files, the trailing `return { ... }` is rewritten to
        `Data_<name> = { ... }`.
    5.  The boot function at the end wires it all together.

Key insight: in Lua, a "return" at the top level of a chunk only
matters for the chunk's return value. Replacing it with an assignment
statement is legal and exposes the value as a top-level local.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, "src")
OUT  = os.path.join(ROOT, "versus_airlines.lua")

HEADER = r"""--[[
    Versus-Airlines :: single-file build
    -------------------------------------
    Auto-generated by scripts/build_singlefile.py.
    DO NOT EDIT. Regenerate with `python3 scripts/build_singlefile.py`.

    Load:
        loadstring(game:HttpGet("<host>/versus_airlines.lua"))()

    Version:  1.3-slice13
    Source:   https://github.com/Aditya-lua/Versus-Airlines
]]

"""

FOOTER = r"""
-- ============================================================================
-- Boot
-- ============================================================================
local function boot()
    -- 1. Mount the Versus window.
    local Library = Window.create()
    if not Library then
        warn("[Versus-Airlines] window mount failed; aborting boot")
        return nil
    end

    -- 2. Boot the kernel graph.
    local kernel = Kernel.boot(Library)
    if not kernel then
        warn("[Versus-Airlines] kernel boot failed; aborting")
        return nil
    end

    -- 3. Register all 11 toggle modules.
    kernel.registry:register(mod_autofarm)
    kernel.registry:register(mod_bring)
    kernel.registry:register(mod_boss)
    kernel.registry:register(mod_fruit)
    kernel.registry:register(mod_sea_event)
    kernel.registry:register(mod_raid)
    kernel.registry:register(mod_v4)
    kernel.registry:register(mod_esp)
    kernel.registry:register(mod_teleport)
    kernel.registry:register(mod_party)
    kernel.registry:register(mod_progression)

    -- 4. Mount the section tree.
    Sections.build(Library, kernel)

    -- 5. Start the live status label.
    Status.start(kernel)

    -- 6. Start the watchdog.
    if kernel.watchdog and kernel.watchdog.start then
        kernel.watchdog:start()
    end

    -- 7. Eager-warm the services cache.
    if kernel.services and kernel.services.init then
        kernel.services:init()
    end

    -- 8. Probe the current game.
    if kernel.game and kernel.game.detectSea then
        local sea = kernel.game:detectSea()
        if sea == 0 then
            kernel.events:emit("milestone", { text = "not in Blox Fruits (or unknown placeId)", level = "warn" })
        end
    end

    -- 9. Load the data tables (now in-file as Data_* locals).
    if kernel.data and kernel.data.loadAll then
        kernel.data:loadAll()
    end

    -- 10. Boot complete.
    return kernel
end

-- ============================================================================
-- Inlined data tables: register each with the kernel's data registry
-- at load time. This is a no-op if the registry's loadAll uses
-- require() (it does, on disk) but in single-file mode we need to
-- inject the tables manually.
-- ============================================================================
do
    -- After Kernel.boot, kernel.data is built. We register our
    -- in-memory tables now so the registry's :get() finds them.
    if _G.VersusKernel and _G.VersusKernel.data then
        local d = _G.VersusKernel.data
        d._tables = d._tables or {}
        d._tables.sea1_quests    = Data_sea1_quests
        d._tables.sea2_quests    = Data_sea2_quests
        d._tables.sea3_quests    = Data_sea3_quests
        d._tables.bosses         = Data_bosses
        d._tables.swords         = Data_swords
        d._tables.fighting_styles= Data_fighting_styles
        d._tables.fruits         = Data_fruits
        d._tables.accessories    = Data_accessories
        d._tables.guns           = Data_guns
        d._tables.materials      = Data_materials
        d._tables.raids          = Data_raids
        d._tables.race_v4        = Data_race_v4
        d._tables.sea_events     = Data_sea_events
        d._tables.islands        = Data_islands
        d._tables.quest_npcs     = Data_quest_npcs
        d._tables.fruit_dealers  = Data_fruit_dealers
        d._tables.enemy_spawn_db = Data_enemy_spawn_db
    end
end

-- Auto-run on load. The user can also call boot() themselves.
local _kernel = boot()
return _kernel
"""

# ---------------------------------------------------------------------------
# Dependency order. Each entry: (relative_path, module_local_name).
# ---------------------------------------------------------------------------
ORDER = [
    # Kernel leaves
    ("src/kernel/compat.lua",     "KernelCompat"),
    ("src/kernel/connection.lua", "KernelConnection"),
    ("src/kernel/registry.lua",   "KernelRegistry"),
    ("src/kernel/stealth.lua",    "KernelStealth"),
    ("src/kernel/watchdog.lua",   "KernelWatchdog"),
    ("src/kernel/events.lua",     "KernelEvents"),
    ("src/kernel/data.lua",       "KernelData"),
    # Game leaves (no src/* deps)
    ("src/game/services.lua",     "GameServices"),
    ("src/game/blox_fruits.lua",  "GameBloxFruits"),
    ("src/game/movement.lua",     "GameMovement"),
    ("src/game/quest.lua",        "GameQuest"),
    ("src/game/mob.lua",          "GameMob"),
    ("src/game/combat.lua",       "GameCombat"),
    ("src/game/bring.lua",        "GameBring"),
    ("src/game/boss.lua",         "GameBoss"),
    ("src/game/fruit.lua",        "GameFruit"),
    ("src/game/sea_event.lua",    "GameSeaEvent"),
    ("src/game/raid.lua",         "GameRaid"),
    ("src/game/v4_trial.lua",     "GameV4Trial"),
    ("src/game/esp.lua",          "GameEsp"),
    ("src/game/teleport.lua",     "GameTeleport"),
    ("src/game/party.lua",        "GameParty"),
    ("src/game/stat.lua",         "GameStat"),
    ("src/game/enhance.lua",      "GameEnhance"),
    ("src/game/mastery.lua",      "GameMastery"),
    # Kernel init (depends on all the above)
    ("src/kernel/init.lua",       "Kernel"),
    # Module leaves
    ("src/modules/mod_autofarm.lua",    "mod_autofarm"),
    ("src/modules/mod_bring.lua",       "mod_bring"),
    ("src/modules/mod_boss.lua",        "mod_boss"),
    ("src/modules/mod_fruit.lua",       "mod_fruit"),
    ("src/modules/mod_sea_event.lua",   "mod_sea_event"),
    ("src/modules/mod_raid.lua",        "mod_raid"),
    ("src/modules/mod_v4.lua",          "mod_v4"),
    ("src/modules/mod_esp.lua",         "mod_esp"),
    ("src/modules/mod_teleport.lua",    "mod_teleport"),
    ("src/modules/mod_party.lua",       "mod_party"),
    ("src/modules/mod_progression.lua", "mod_progression"),
    # UI leaves
    ("src/ui/window.lua",     "Window"),
    ("src/ui/sections.lua",   "Sections"),
    ("src/ui/status.lua",     "Status"),
]

DATA_ORDER = [
    "accessories",  "bosses",         "enemy_spawn_db",  "fighting_styles",
    "fruit_dealers","fruits",         "guns",            "islands",
    "materials",    "quest_npcs",     "race_v4",         "raids",
    "sea1_quests",  "sea2_quests",    "sea3_quests",     "sea_events",
    "swords",
]

# Map "src.kernel.compat" -> "KernelCompat" (must match ORDER keys).
def dotted_to_local(dotted):
    parts = dotted.split(".")
    if len(parts) < 3 or parts[0] != "src":
        return None
    if parts[1] == "kernel":
        if len(parts) == 3:
            return "Kernel" + parts[2].capitalize()
        if len(parts) == 2:
            return "Kernel"
    if parts[1] == "game":
        if len(parts) == 3:
            return "Game" + parts[2].capitalize()
        if len(parts) == 4 and parts[2] == "data":
            return "Data_" + parts[3]
    if parts[1] == "modules":
        return "mod_" + parts[2]
    if parts[1] == "ui":
        return parts[2].capitalize()
    return None

# Strip the `-- Mined from ...` header comments from data files —
# they reference the original repo path. Keep the body intact.
MINE_HEADER_RE = re.compile(
    r'--\[\[\s*\n\s*Versus-Airlines\s*::\s*src/game/data/.*?\]\]',
    re.DOTALL,
)
MINE_INLINE_RE = re.compile(r'\s*---\s*Mined from[^"]*---\s*')

# Replace require("src.X.Y") -> require("script.Parent.X.Y") is the
# roblox idiom. In single-file mode we want require("src.X.Y") ->
# <local name>. We also accept the Roblox-style `require(script.Parent.X.Y)`.
REQUIRE_DOTTED_RE = re.compile(
    r'require\(\s*script\.Parent\.([\w\.]+?)\s*\)'
)
REQUIRE_SRC_RE = re.compile(
    r'require\(\s*["\']\s*(src\.[\w\.]+?)\s*["\']\s*\)'
)

def rewrite_requires(body):
    def sub_dotted(m):
        target = dotted_to_local("src." + m.group(1))
        if target is None:
            return "nil  -- unresolved: " + m.group(1)
        return target
    def sub_src(m):
        target = dotted_to_local(m.group(1))
        if target is None:
            return "nil  -- unresolved: " + m.group(1)
        return target
    body = REQUIRE_DOTTED_RE.sub(sub_dotted, body)
    body = REQUIRE_SRC_RE.sub(sub_src, body)
    return body

# Replace a trailing `return X` with `X = <expr>` so the value is
# exposed as a top-level local. We anchor on the LAST `return` in
# the file (modules always end with one) AND require it to be at
# column 0 (no indent) so we don't accidentally rewrite a
# function body's `return` statement.
def replace_trailing_return(body, target):
    lines = body.split("\n")
    last_idx = -1
    for i in range(len(lines) - 1, -1, -1):
        line = lines[i]
        # Only match column-0 return statements.
        if re.match(r'^return\s+', line):
            last_idx = i
            break
    if last_idx == -1:
        return body  # no return; shouldn't happen for our files
    expr = re.sub(r'^return\s+', '', lines[last_idx]).rstrip()
    lines[last_idx] = f"{target} = {expr}"
    return "\n".join(lines)

def transform_file(path, target, is_data=False):
    full = os.path.join(ROOT, path)
    with open(full, "r") as f:
        body = f.read()

    body = rewrite_requires(body)

    if is_data:
        # Strip the "Mined from ..." header to save bytes.
        body = MINE_HEADER_RE.sub("", body, count=1)
        body = MINE_INLINE_RE.sub("", body)

    body = replace_trailing_return(body, target)
    return body

def main():
    parts = [HEADER]
    parts.append("-- ============================================================================\n")
    parts.append("-- Kernel leaves\n")
    parts.append("-- ============================================================================\n\n")
    for path, target in ORDER:
        if path.startswith("src/kernel/init"):
            parts.append("\n-- ============================================================================\n")
            parts.append("-- Kernel init (after all leaves)\n")
            parts.append("-- ============================================================================\n\n")
        parts.append(f"-- {path}\n")
        parts.append(transform_file(path, target))
        parts.append("\n\n")

    parts.append("\n-- ============================================================================\n")
    parts.append("-- Data tables (inlined from src/game/data/*.lua)\n")
    parts.append("-- ============================================================================\n\n")
    for d in DATA_ORDER:
        path = f"src/game/data/{d}.lua"
        target = f"Data_{d}"
        parts.append(f"-- {path}\n")
        parts.append(transform_file(path, target, is_data=True))
        parts.append("\n\n")

    parts.append(FOOTER)

    with open(OUT, "w") as f:
        f.write("".join(parts))
    print(f"wrote {OUT} ({sum(len(p) for p in parts):,} bytes)")

if __name__ == "__main__":
    main()
